### ISSUE TITLE
Alternative to syncing files

### ISSUE THREAD

**Issue by midzelis** [kgorlen/lightroom#1]
Just found out that an alternative to syncing files works perfectly -- using windows junctions (like linux symbolic links) 

https://hugoideler.com/2020/10/saving-adobe-lightroom-catalogs-to-network-drives-on-windows/

**Comment by kgorlen** [comment]
An advantage of using a junction instead of `subst` is that the junction and symlink are persistent, eliminating the need to run `catmap.bat` at startup.  I like the idea, and I'm trying it out.
